// <auto-generated />
using System;
using ClusterWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClusterWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250221155945_RemoveResidenteIdFromPagos")]
    partial class RemoveResidenteIdFromPagos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClusterWeb.Entities.Casa", b =>
                {
                    b.Property<int>("CasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CasaId"));

                    b.Property<int>("Banos")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCasa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CasaId");

                    b.HasIndex("Direccion")
                        .HasDatabaseName("idx_direccion");

                    b.ToTable("Casas");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Deuda", b =>
                {
                    b.Property<int>("DeudaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeudaId"));

                    b.Property<int>("CasaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DeudaId");

                    b.HasIndex("CasaId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<int>("DeudaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ResidenteId")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.HasIndex("DeudaId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Residente", b =>
                {
                    b.Property<int>("ResidenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenteId"));

                    b.Property<int>("CasaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidenteId");

                    b.HasIndex("CasaId");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("idx_nombre");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Deuda", b =>
                {
                    b.HasOne("ClusterWeb.Entities.Casa", "Casa")
                        .WithMany("Deudas")
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClusterWeb.Entities.Residente", "Residente")
                        .WithMany("Deudas")
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Pago", b =>
                {
                    b.HasOne("ClusterWeb.Entities.Deuda", "Deuda")
                        .WithMany()
                        .HasForeignKey("DeudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClusterWeb.Entities.Residente", null)
                        .WithMany("Pagos")
                        .HasForeignKey("ResidenteId");

                    b.Navigation("Deuda");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Residente", b =>
                {
                    b.HasOne("ClusterWeb.Entities.Casa", "Casa")
                        .WithMany("Residentes")
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Casa", b =>
                {
                    b.Navigation("Deudas");

                    b.Navigation("Residentes");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Residente", b =>
                {
                    b.Navigation("Deudas");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
