// <auto-generated />
using System;
using ClusterWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClusterWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClusterWeb.Entities.Casa", b =>
                {
                    b.Property<int>("IdCasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCasa"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroCasa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCasa");

                    b.HasIndex("NumeroCasa")
                        .IsUnique()
                        .HasDatabaseName("idx_numero_casa");

                    b.ToTable("Casas");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Cuota", b =>
                {
                    b.Property<int>("IdCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuota"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCasa")
                        .HasColumnType("int");

                    b.Property<int>("IdResidente")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NombreCuota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCuota");

                    b.HasIndex("IdCasa");

                    b.HasIndex("IdResidente");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCasa")
                        .HasColumnType("int");

                    b.Property<int>("IdCuota")
                        .HasColumnType("int");

                    b.Property<int?>("IdResidente")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdCasa");

                    b.HasIndex("IdCuota");

                    b.HasIndex("IdResidente");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Residente", b =>
                {
                    b.Property<int>("IdResidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResidente"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdCasa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResidente");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_email");

                    b.HasIndex("IdCasa");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Cuota", b =>
                {
                    b.HasOne("ClusterWeb.Entities.Casa", "Casa")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdCasa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClusterWeb.Entities.Residente", "Residente")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdResidente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Casa");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Pago", b =>
                {
                    b.HasOne("ClusterWeb.Entities.Casa", "Casa")
                        .WithMany()
                        .HasForeignKey("IdCasa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClusterWeb.Entities.Cuota", "Cuota")
                        .WithMany()
                        .HasForeignKey("IdCuota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClusterWeb.Entities.Residente", "Residente")
                        .WithMany("Pagos")
                        .HasForeignKey("IdResidente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Casa");

                    b.Navigation("Cuota");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Residente", b =>
                {
                    b.HasOne("ClusterWeb.Entities.Casa", "Casa")
                        .WithMany("Residentes")
                        .HasForeignKey("IdCasa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Casa", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("Residentes");
                });

            modelBuilder.Entity("ClusterWeb.Entities.Residente", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
